spdx/tools-java

pom.xml
=> Update library dependencies to resolve compare unit test failures

src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
Signed-off-by: Ehtesham <ehteshamkhan3014@gmail.com>
Java Doc param removed #10
=> Removed a javaDoc param

CONTRIBUTING.md, src/main/java/org/spdx/tools/Main.java, src/main/java/org/spdx/tools/SpdxToolsHelper.java
Resolves issue #23 
This PR also updates the release version in the source
=> Add CONTRIBUTING.md file

src/main/java/org/spdx/tools/schema/AbstractOwlRdfConverter.java, src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
Updates the JSON Schema generator to be consistent with the current JSON example file.
- Remove the top level Document property
- Add documentNamespace
=> Update JSON schema generation

src/main/java/org/spdx/tools/CompareSpdxDocs.java, src/main/java/org/spdx/tools/compare/DocumentSheet.java
=> Fixes for SPDX compare utility after docfest

src/main/java/org/spdx/tools/RdfSchemaToJsonContext.java, src/main/java/org/spdx/tools/schema/AbstractOwlRdfConverter.java, src/main/java/org/spdx/tools/schema/OwlToJsonContext.java
=> Sort properties for JSON Schema and JSON Context

pom.xml, resources/spdx-schema.json, src/main/java/org/spdx/tools/Verify.java, src/test/java/org/spdx/tools/VerifyTest.java, testResources/BadJSON.spdx.json
=> Add JSON schema verification to Verify

pom.xml
Incorporates fix for issue #38
=> Update SPDX Java Library to version 1.0.9

.github/workflows/build.yml
=> Fix CI failure for users without SPDX access

pom.xml, src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
This change supports the JSON schema updates referenced in https://github.com/spdx/spdx-spec/pull/631
=> Add documentation for describes in the JSON Schema

src/main/java/org/spdx/tools/schema/AbstractOwlRdfConverter.java
=> Add logging for any missing enumeration values when generating schemas

src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
=> Generation missing required properties for arrays

README.md
Signed-off-by: Armin Tänzer <armintaenzer@tngtech.com>
resolves #65
=> updated README to reflect the new file names and structures

dependency-check-supress.xml, pom.xml
=> Add dependency-check util to POM file

pom.xml
=> Update library version

src/main/java/org/spdx/tools/SpdxToolsHelper.java
=> Add filename to message for InvalidFileNameException

pom.xml, src/main/java/org/spdx/tools/compare/AbstractSheet.java
=> Update library versions to 1.1.2

src/main/java/org/spdx/tools/SpdxConverter.java, src/main/java/org/spdx/tools/SpdxToolsHelper.java, src/main/java/org/spdx/tools/Verify.java
Fixes #90
See Jena issue 2331 for more information:
https://issues.apache.org/jira/browse/JENA-2331
=> Set the XMLInputFactory property for RDF files

src/main/java/org/spdx/tools/Main.java
=> Update version in Main.java

README.md
Update jar name in the examples: tools-java-1.1.5-jar-with-dependencies.jar
Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>
=> Update jar name in the examples

src/main/java/org/spdx/tools/SpdxViewer.java, src/main/java/org/spdx/tools/Verify.java
See https://github.com/spdx/spdx-spec/pull/841
=> Update JSON Schema

.github/workflows/build.yml
=> Update CI to use JDK 17

README.md
=> Document supported spec versions

README.md, src/main/java/org/spdx/tools/CompareSpdxDocs.java, src/main/java/org/spdx/tools/SpdxConverter.java, src/main/java/org/spdx/tools/SpdxViewer.java, src/main/java/org/spdx/tools/Verify.java
=> Add JSONLD to the documenation for supported file types

README.md
Update README with the right commands for RC2.
=> Update README with RC2

RELEASE-CHECKLIST.md
=> Add a step to update the README on new releases

resources/spdx-schema-v3.0.1.json, src/test/java/org/spdx/tools/LatestSchemaVersionTest.java, src/test/java/org/spdx/tools/SchemaVersionTest.java
This PR does two things:
1) Update the content of `resources/spdx-schema-v3.0.1.json` (download from https://spdx.org/schema/3.0.1/spdx-json-schema.json)
2) Add a unit test to compare the content of the latest version of local JSON schema file with its remote counterpart
To resolve, the schema part, of #183
=> Add a test- case to flag if the JSON Schema file need to be updated

pom.xml
- Update spdx-maven-plugin to 1.0.0
- Update other dependencies to latest patch version
=> spdx-maven-plugin == 1.0.0

pom.xml
- spdx-maven-plugin to 1.0.2
- spdx-jackson-store to 2.0.2
=> Update spdx-maven-plugin and spdx-jackson-store

.github/workflows/docs.yml
Will publish to https://spdx.github.io/tools-java/
=> Add Javadoc build workflow
