- src/main/java/org/spdx/tools/SpdxToolsHelper.java
Signed-off-by: Ehtesham <ehteshamkhan3014@gmail.com>
Verify should support file extension "yml" #8
> Accept YML

- src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
Signed-off-by: Ehtesham <ehteshamkhan3014@gmail.com>
Removed jsonMapper as a param from the javadoc #10
> Removed jsonMapper as a param from the javadoc

- pom.xml
- src/main/java/org/spdx/tools/SpdxConverter.java
Update library versions to the latest - resolves significant performance problem when parsing large SPDX files.
Also fixes a formatting issues for error text in the compare utility.
> Update library versions

- src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
Include `additionalProperties=false` and add missing properties for `SinglePointer`
> Update JSON Schema generation

- README.md
Update convertible SPDX format
Fix incorrect spdx conversion example
Resolves #33
Signed-off-by: riyenas0925 <riyenas0925@gmail.com>
> Update SPDX format converters part of README.md

- README.md
- examples/org/spdx/examples/SimpleSpdxDocument.java
> Add an example for creating an SPDX document

- src/main/java/org/spdx/tools/compare/PackageSheet.java
This resolves an issue where an exception occurs when the copyright text
exceeds the maximum text size for a spreadsheet when running a compare
> Check for copyright size in compare

- README.md
The readme had a broken link to the SPDX online tool - I presume it should link to https://tools.spdx.org/app/validate/? I changed the readme link for this PR
> Update link to SPDX online tool

- examples/org/spdx/examples/ExistingSpdxDocument.java
> Add example for accessing existing SPDX objects

- resources/spdx-schema-v2.3.json
- src/test/java/org/spdx/tools/VerifyTest.java
Allows for both dashes and underscores in enumeration values
Supports spec resolution for https://github.com/spdx/spdx-spec/issues/792
> Update JSON schema

- src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
See https://github.com/spdx/spdx-spec/issues/795 for context on documentDescribes
See https://github.com/spdx/spdx-spec/issues/792 for context on enum underscores
> Update schema generator for required fields

- src/main/java/org/spdx/tools/SpdxConverter.java
- src/main/java/org/spdx/tools/SpdxToolsHelper.java
> Add support for RDF Turtle format

- src/main/java/org/spdx/tools/schema/OwlToJsonContext.java
- src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
- src/main/java/org/spdx/tools/schema/OwlToXsd.java
> Add extra checks for NPE on getUri()

- pom.xml
Fixes #88
This change was needed to properly load Jena
See https://jena.apache.org/documentation/notes/jena-repack.html
> Change maven assembly to shade for jar-with-dependencies

- .github/workflows/docker_deploy.yml
- Dockerfile
- scripts/tools-java-wrapper.sh
@goneall Please consider make the gh packages repository for spdx public, so anyone can pull this image without the need to signin on github
> feature(docker): Create docker container and push to ghcr

- pom.xml
- src/main/java/org/spdx/tools/Main.java
The indirect dependency on Apache Jena requires Java 11
This commit updates the POM file to reflect the correct Java versions in the POM file
> Update POM with correct Java versions

- pom.xml
This PR also updates the POM file to enforce Java 11 which is required due to an indirect dependency on Apache Jena
> Update SPDX libraries to version 1.1.4

- pom.xml
- src/main/java/org/spdx/tools/Main.java
- src/main/java/org/spdx/tools/SpdxVersion.java
- src/main/resources/project.properties
- Resolves https://github.com/spdx/tools-java/issues/112
Add SpdxVersion class to store and handle version information of tools, library and license list.
> Add API to get version information

- src/main/java/org/spdx/tools/Verify.java
Improves error messages.  Previously, a JSON parsing error would be reported as a file I/O error.
> Catch JSON exceptions in verify

- src/main/java/org/spdx/tools/SpdxViewer.java
> Support JSON, YAML, XML (and tag/value) file types for SPDX Viewer

- src/main/java/org/spdx/tools/Verify.java
> Only warn for verify deprecated license IDs

- src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java
Also adds a '$schema' field.
Fixes #144
> Update OWL schema to include deprecated

- README.md
The examples should use the jar file from versions 1.1.8
> Update README.md to version 1.1.8

- pom.xml
fixes #153 (hopefully)
Merge this pull request only if tools-java is used as a command line tool and is not intended to be used as a maven dependency for other artifacts. If so, this fix will force the use of slf4j-simple (console logging) in the other artifact (or requires <excludes>).
For the explanation related to comments in #153 : when using the uberjar / jar-with-dependencies, it is not enough to add slf4j-simple in the classpath. The reason is that some `org.slf4j` package exists inside the produced jar with dependencies. So, adding `slf4j-simple` to the classpath is probably ignored, but when added as a maven dependency, it will be included in the `jar-with-dependencies` and it will work.
The result of some `Verfify` with the built jar does not include the fl4j warning anymore and …
> adding slf4j-simple as a dependency, as uber jar won't allow using it via classpath

- src/main/java/org/spdx/tools/compare/PackageSheet.java
- testResources/sourcefiles/PackageSheet.java
- variable: `packagComparers` -> `packageComparers`
- This variable is internal, it is safe to be renamed
- protected method: `exludeFilesToString` -> `excludeFilesToString`
- This method is protected, only accessible to within the same package and by subclasses
- If there is a known subclass of `org.spdx.tools.compare.PackageSheet` accessing this method, outside of this package, it may not safe to be renamed
- The file method is available since 23 Sep 2020
> Fix typos in variable and protected method names

- src/main/java/org/spdx/tools/compare/PackageSheet.java
- testResources/sourcefiles/PackageSheet.java
protected static final String DOWNLOAD_FIELD_TEXT:
- "Dowload Location" -> "Download Location"
Note that this change may affect code that expected the misspelled value.
> Fix typo for DOWNLOAD_FIELD_TEXT value

- src/main/java/org/spdx/tools/MatchingStandardLicenses.java
- src/main/java/org/spdx/tools/Verify.java
- src/main/java/org/spdx/tools/compare/CreatorSheet.java
- src/main/java/org/spdx/tools/compare/DocumentSheet.java
- src/main/java/org/spdx/tools/compare/PackageSheet.java
- testResources/sourcefiles/DocumentSheet.java
- Check if a return value from `getCreationInfo()` or `getLicenseDeclared()` is null before access.
- Suppress one null warning for a command line that null is already checked
> Handle null before access to creation info / license info

- src/main/java/org/spdx/tools/Main.java
This fixes a failure when executing the version command.
Note that multiple calls to init will not cause any issue and has minimal performance impact.
> Initialize models in the Main

- .github/workflows/build.yml
`actions/cache@v1` is outdated and no longer able to download/run.
> Update outdated/no longer available GitHub Actions

- pom.xml
- java-spdx-library to 2.0.0
- spdx-rdf-store to 2.0.0
- spdx-jackson-store to 2.0.0
- spdx-spreadsheet-store to 2.0.0
- spdx-tagvalue-store to 2.0.0
- spdx-v3jsonld-store to 1.0.0
- Update other dependencies to the their latest patch version
- Update org.apache.poi/poi from 5.3.0 to 5.4.1 to fix errors in 4 tests
> Update SPDX libraries version in POM

- src/test/java/org/spdx/tools/LatestSchemaVersionTest.java
- "new URL()" is deprecated in Java 20
- Use recommended URI.create().toURL() (available since Java 1.4)
> Use URI.create().toURL() instead of the deprecated URL() constructor

- src/test/java/org/spdx/tools/LatestSchemaVersionTest.java
Fixes an issue where the compare fails if run on a windows environment where CRLF is used instead of LF
> Normalize whitespace in schema compare unit test

- pom.xml
Fixes #201
Later versions of the shade plugin strip out the dependencies in the POM file.
> Fix Shade plugin version to 3.2.4

- README.md
- Update JAR name in command line examples to version 2.0.0
- Fix few Markdown issues
- Add Javadoc link
> Update JAR name in command line examples to 2.0.0

- resources/spdx-schema-v2.3.json
For Wolfi container at cgr.dev/chainguard/wolfi-base, trivy for spdx json SBOM generates
```json
{
"name": "wolfi",
"SPDXID": "SPDXRef-OperatingSystem-2bccf727fe0bc7f8",
"versionInfo": "20230201",
"downloadLocation": "NONE",
"filesAnalyzed": false,
"primaryPackagePurpose": "OPERATING-SYSTEM",
"annotations": [
{
"annotator": "Tool: trivy-0.62.1",
"annotationDate": "2025-05-28T17:07:25Z",
"annotationType": "OTHER",
"comment": "Class: os-pkgs"
},
{
"annotator": "Tool: trivy-0.62.1",
"annotationDate": "2025-05-28T17:07:25Z",
"annotationType": "OTHER",
"comment": "Type: wolfi"
}
]
}
```
Which fails validating with tools-java because "OPERATING-SYSTEM" value is with a dash, which matches the spec at https://spdx.github.io/spdx-spec/v2.3/package-information/#724-primary-package-purpose-field …
> spdx-schema-v2.3.json: fix OPERATING-SYSTEM package intent

- pom.xml
- src/main/java/org/spdx/tools/Verify.java
Fixes #229
Also updates the Verify.java file to remove JavaDoc warnings and a few other minor cleanups
> Update JavaDocs config
